### ISSUE TITLE
Error - Gen2 Camera Demo

### ISSUE THREAD

**Issue by dhruvsheth-ai** [luxonis/depthai-experiments#106]
This might have been referenced too many times, but I'm opening this over here for reference. 
The gen2-camera-demo starts for a few seconds, and closes immidiately triggering an error - 

```python
StereoDepth config options:
    Left-Right check:   True
    Extended disparity: False
    Subpixel:           True
    Median filtering:   MedianFilter.MEDIAN_OFF
Creating Stereo Depth pipeline: MONO CAMS -> STEREO -> XLINK OUT
Creating DepthAI device
Starting pipeline
Traceback (most recent call last):
  File "main.py", line 306, in <module>
    test_pipeline()
  File "main.py", line 296, in test_pipeline
    image = q.get()
RuntimeError: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'depth' (X_LINK_ERROR)'
```

Sometimes with the error - 
```python
StereoDepth config options:
    Left-Right check:   True
    Extended disparity: False
    Subpixel:           True
    Median filtering:   MedianFilter.MEDIAN_OFF
Creating Stereo Depth pipeline: MONO CAMS -> STEREO -> XLINK OUT
Creating DepthAI device
Starting pipeline
Segmentation fault
```

It is using updated lib - depthai==2.0.0.1, and running the stereo demo, not point cloud, since it's running on armv7l - Rpi 4b 8gb

I checked the CPU load, and it was barely any, but still reciprocating an error.
Have kept this open for reference.

**Comment by Luxonis-Brandon** [comment]
@csaba-luxonis - does this have anything to do with what you just addressed?

**Comment by Luxonis-Brandon** [comment]
Thanks.  Asking.

**Comment by dhruvsheth-ai** [comment]
No issues, had closed it bymistake.
