### ISSUE TITLE
Missing scipy dependency in requirements.txt for collision-avoidance

### ISSUE THREAD

**Issue by billythedummy** [luxonis/depthai-experiments#117]
Throws the following error:

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from tracker import Tracker
  File "/home/user/collision-avoidance/tracker.py", line 4, in <module>
    from scipy.spatial import distance as dist
ModuleNotFoundError: No module named 'scipy'
```

**Comment by Luxonis-Brandon** [comment]
Thanks @billythedummy .  So we're about to update this to Gen2.  Maybe worth just fixing this in the meantime @Erol444 ?

**Comment by Erol444** [comment]
Added a PR that fixes this issue. Thanks for reporting @billythedummy!
