### ISSUE TITLE
Incompatible constructor error for depthai.Device in collision-avoidance

### ISSUE THREAD

**Issue by wujiang** [luxonis/depthai-experiments#168]
`depthai-python` version: 2.8.0.0

error:

```
wu@nx:~/workspace/github/luxonis/depthai-experiments/collision-avoidance$ python3 main.py
2021-07-26 17:30:10,414 - root - INFO - Logging system initialized, kept in file /home/wu/workspace/github/luxonis/depthai-experiments/collision-avoidance/camera.log...
2021-07-26 17:30:10,737 - __main__ - INFO - Setting up debug run...
Traceback (most recent call last):
  File "/home/wu/workspace/github/luxonis/depthai-experiments/collision-avoidance/main.py", line 121, in <module>
    MainDebug().run()
  File "/home/wu/workspace/github/luxonis/depthai-experiments/collision-avoidance/main.py", line 47, in __init__
    super().__init__()
  File "/home/wu/workspace/github/luxonis/depthai-experiments/collision-avoidance/main.py", line 19, in __init__
    self.depthai = self.depthai_class(model_name="vehicle-detection-adas-0002", threshold=0.5)
  File "/home/wu/workspace/github/luxonis/depthai-experiments/collision-avoidance/depthai_utils.py", line 65, in __init__
    super().__init__(*args, **kwargs)
  File "/home/wu/workspace/github/luxonis/depthai-experiments/collision-avoidance/depthai_utils.py", line 24, in __init__
    self.pipeline = self.create_pipeline({
  File "/home/wu/workspace/github/luxonis/depthai-experiments/collision-avoidance/depthai_utils.py", line 14, in create_pipeline
    self.device = depthai.Device('', False)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. depthai.Device(pipeline: depthai.Pipeline)
    2. depthai.Device(pipeline: depthai.Pipeline, usb2Mode: bool)
    3. depthai.Device(pipeline: depthai.Pipeline, pathToCmd: str)
    4. depthai.Device(pipeline: depthai.Pipeline, deviceDesc: depthai.DeviceInfo, usb2Mode: bool = False)
    5. depthai.Device(pipeline: depthai.Pipeline, deviceDesc: depthai.DeviceInfo, pathToCmd: str)
    6. depthai.Device(version: depthai.OpenVINO.Version = <Version.VERSION_2021_4: 5>)
    7. depthai.Device(version: depthai.OpenVINO.Version, usb2Mode: bool)
    8. depthai.Device(version: depthai.OpenVINO.Version, pathToCmd: str)
    9. depthai.Device(version: depthai.OpenVINO.Version, deviceDesc: depthai.DeviceInfo, usb2Mode: bool = False)
    10. depthai.Device(version: depthai.OpenVINO.Version, deviceDesc: depthai.DeviceInfo, pathToCmd: str)

Invoked with: '', False
Exception ignored in: <function DepthAIDebug.__del__ at 0x7f8c431ee0>
Traceback (most recent call last):
  File "/home/wu/workspace/github/luxonis/depthai-experiments/collision-avoidance/depthai_utils.py", line 86, in __del__
    super().__del__()
  File "/home/wu/workspace/github/luxonis/depthai-experiments/collision-avoidance/depthai_utils.py", line 60, in __del__
    del self.device
AttributeError: device
```

**Comment by Luxonis-Brandon** [comment]
Thanks for the report.  CC: @VanDavv here.

**Comment by Erol444** [comment]
Hello @wujiang,
the collision avoidance experiment hasn't been merged to gen2 depthai API, so it's still at gen1. Based on the error message I believe you have gen2 depthai installed. You should install requirements of that experiments (`python3 -mpip install -r requirements.txt`) and try again.
Thanks, Erik

**Comment by wujiang** [comment]
understood. It works. Thank you @Erol444
