### ISSUE TITLE
Runtime error: Human pose estimation doesn't work :(

### ISSUE THREAD

**Issue by 28anmol** [luxonis/depthai-experiments#340]
Greetings!!

I am trying to deploy gen2-human pose on an oak-d lite camera, with all the requirements installed as per the instruction set given in the corresponding document: [readme](https://github.com/luxonis/depthai-experiments/tree/master/gen2-human-pose)
but I get the following runtime error: device not found (even though the device is connected)

(venv) anmolsingh@ANMOLs-MacBook-Pro ProjectPython % python3 main.py -cam                      
Traceback (most recent call last):
  File "/Users/anmolsingh/Desktop/ProjectPython/main.py", line 23, in <module>
    device_info = getDeviceInfo()
  File "/Users/anmolsingh/Desktop/ProjectPython/venv/lib/python3.9/site-packages/depthai_sdk/utils.py", line 137, in getDeviceInfo
    raise RuntimeError("No DepthAI device found!")
RuntimeError: No DepthAI device found!

Help on this account would be extremely appreciated.

Thanks and regards,
Anmol.

**Comment by 28anmol** [comment]
Greetings!!

Nevermind! The code worked. USB to USB C cable was creating problems! Thanks!
