### ISSUE TITLE
gen2-mjpeg-streaming does not work streamed frames

### ISSUE THREAD

**Issue by jaiminlee** [luxonis/depthai-experiments#368]
I try runing http://localhost:8090. but It's not work.
is this bug?

127.0.0.1 - - [15/Jun/2022 14:14:42] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 43776)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "main.py", line 48, in do_GET
    self.end_headers()
  File "/usr/lib/python3.8/http/server.py", line 529, in end_headers
    self.flush_headers()
  File "/usr/lib/python3.8/http/server.py", line 533, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/usr/lib/python3.8/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by jaiminlee** [comment]
It do not work in FireFox.

**Comment by jaiminlee** [comment]
p{margin-top:0;margin-bottom:0}
    


    Thank you. Erik.

You are right.

there is nothing problem in code.


--------- 원본 메일 ---------

    
        보낸사람: Erik ***@***.***>
        받는사람: luxonis/depthai-experiments ***@***.***>
        
            참조: jaiminlee ***@***.***>, Mention ***@***.***>
        
        날짜: 22.06.16 00:19 GMT +0900
        제목: Re: [luxonis/depthai-experiments] gen2-mjpeg-streaming does not work streamed frames (Issue #368)
        
        
    
    
        
@jaiminlee Have you tried with Chrome? In readme of this demo it's written:
To see the streamed frames, open localhost:8090. This works in Chrome, but not Firefox or Safari.
Thanks, Erik

**Comment by Erol444** [comment]
Perfect, thanks for testing and confirming!
