### ISSUE TITLE
gen2-face-recognition crashes

### ISSUE THREAD

**Issue by cirenehc** [luxonis/depthai-experiments#371]
`$ python3 main.py `

Crashes with the following error message

```
Traceback (most recent call last):
  File "main.py", line 259, in <module>
    conf, name = facerec.new_recognition(features)
  File "main.py", line 72, in new_recognition
    conf_ = self.cosine_distance(j, results)
  File "main.py", line 60, in cosine_distance
    if a.shape != b.shape:
AttributeError: 'bytes' object has no attribute 'shape'
```

**Comment by cirenehc** [comment]
Seems like embedding file for my face is corrupted (since I killed main.py abruptly while it was storing).

**Comment by Erol444** [comment]
Has this been fixed?
