### ISSUE TITLE
imu-frames-timestamp-sync.py  got type error

### ISSUE THREAD

**Issue by ryanESX** [luxonis/depthai-experiments#456]
use oakd-w-pro. And try `python gen2-syncing/imu-frames-timestamp-sync.py` 
it return following message:
```
FPS 931966.4307258327
Traceback (most recent call last):
  File "gen2-syncing/imu-frames-timestamp-sync.py", line 185, in <module>
    new_msg(msg, name, ts)
  File "gen2-syncing/imu-frames-timestamp-sync.py", line 153, in new_msg
    print(f"[Seq {rgb.getSequenceNum()}] Mid of RGB exposure ts: {td2ms(rgb_ts)}ms, RGB ts: {td2ms(rgb.getTimestampDevice())}ms, RGB exposure time: {td2ms(rgb.getExposureTime(), exposure=True)}ms")
```
I used `depthai-2.20.2.0`

**Comment by Erol444** [comment]
Hi @ryanESX ,
Could you copy the full error message?
Thanks, Erik
