### ISSUE TITLE
Update & improve gen2 color isp raw example

### ISSUE THREAD

**Issue by VanDavv** [luxonis/depthai-experiments#58]
I tried to migrate this example to latest DepthAI Gen2 API (commit hash ``), and got the following error after running against this version

```
Traceback (most recent call last):
  File "/home/vandavv/dev/luxonis/depthai-experiments/gen2-color-isp-raw/main.py", line 40, in <module>
    cam.setEnablePreviewStillVideoStreams(False)
AttributeError: 'depthai.ColorCamera' object has no attribute 'setEnablePreviewStillVideoStreams'
```

This example also lacks a fixed requirements version, README.md and command line parameters

**Comment by themarpe** [comment]
I think that this targets @alex-luxonis branch https://github.com/luxonis/depthai-python/tree/gen2_imagemanip_rotate

**Comment by alex-luxonis** [comment]
It's based on https://github.com/luxonis/depthai-python/compare/gen2_develop...gen2_camera_isp_raw
And there's a local `requirements.txt` pointing to a working depthai library for now. I'll integrate with the latest.

**Comment by VanDavv** [comment]
Thanks!

**Comment by franva** [comment]
Hi @VanDavv @alex-luxonis and @themarpe , this issue comes back on version 2.9.0.0. I am running the `depthai_demo.py` on RPi 4 with Python 3.7.3 all dependencies installed.

```
$ python3 depthai_demo.py -cnn deeplabv3p_person

/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Using depthai module from:  /home/pi/.local/lib/python3.7/site-packages/depthai.cpython-37m-arm-linux-gnueabihf.so
Depthai version installed:  2.9.0.0
Available devices:
[0] 14442C10013762D700 [X_LINK_UNBOOTED]
Enabling low-bandwidth mode due to low USB speed... (speed: UsbSpeed.HIGH)
Creating MJPEG link for ColorCamera node and color xlink stream...
Traceback (most recent call last):
  File "depthai_demo.py", line 148, in <module>
    pm.create_color_cam(nn_manager.input_size if conf.useNN else conf.previewSize, rgb_res, conf.args.rgb_fps, conf.args.full_fov_nn, xout=Previews.color.name in conf.args.show)
  File "/home/pi/Work/MyBuddy/depthai/depthai_helpers/managers.py", line 662, in create_color_cam
    self.mjpeg_link(self.nodes.cam_rgb, self.nodes.xout_rgb, self.nodes.cam_rgb.video)
  File "/home/pi/Work/MyBuddy/depthai/depthai_helpers/managers.py", line 623, in mjpeg_link
    if isinstance(node, dai.ColorCamera) or isinstance(node, dai.MonoCamera):
AttributeError: module 'depthai' has no attribute 'ColorCamera'
```

**Comment by VanDavv** [comment]
For the reference, issue mentioned by @franva was resolved in this PR - https://github.com/luxonis/depthai/pull/446
