### ISSUE TITLE
Traingulation 3D Visualiser Error

### ISSUE THREAD

**Issue by dhruvsheth-ai** [luxonis/depthai-experiments#73]
I was running different scripts to check the if the required library version runs on the system, while I ran across an error in Traingulation 3D Visualiser, so gave a thought of reporting the error faced on "armv7l" machine-system, i.e 32 bit Raspbian OS.
Here's the error -
```shell
(venv2) pi@raspberrypi:~/depthai-experiments/triangulation-3D-visualizer $ python3 main.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
XLink initialized.
Sending internal device firmware
Successfully connected to device.
Loading config file
Attempting to open stream config_d2h
watchdog started 
Successfully opened stream config_d2h with ID #0!
Closing stream config_d2h: ...
Closing stream config_d2h: DONE.
EEPROM data: valid (v5)
  Board name     : BW1098OBC
  Board rev      : R0M0E0
  HFOV L/R       : 71.86 deg
  HFOV RGB       : 68.7938 deg
  L-R   distance : 7.5 cm
  L-RGB distance : 3.75 cm
  L/R swapped    : yes
  L/R crop region: center
  Rectification Rotation R1 (left):
    0.999987,    0.004518,    0.002240,
   -0.004518,    0.999990,    0.000004,
   -0.002240,   -0.000014,    0.999997,
  Rectification Rotation R2 (right):
    0.999996,   -0.002422,   -0.001414,
    0.002422,    0.999997,   -0.000010,
    0.001414,    0.000007,    0.999999,
  Calibration intrinsic matrix M1 (left):
  857.518066,    0.000000,  637.386780,
    0.000000,  858.455322,  404.491150,
    0.000000,    0.000000,    1.000000,
  Calibration intrinsic matrix M2 (right):
  856.180054,    0.000000,  640.267273,
    0.000000,  856.741455,  398.091125,
    0.000000,    0.000000,    1.000000,
  Calibration rotation matrix R:
    0.999969,    0.006940,    0.003653,
   -0.006941,    0.999976,    0.000005,
   -0.003653,   -0.000031,    0.999993,
  Calibration translation matrix T:
   -7.513971,
    0.018201,
    0.010622,
  Calibration Distortion Coeff d1 (Left):
   -5.192124,   16.073618,    0.000318,   -0.000139,  -16.213690,   -5.244258,   16.288498,
  -16.425783,    0.000000,    0.000000,    0.000000,    0.000000,    0.000000,    0.000000,
  Calibration Distortion Coeff d2 (Right):
   41.654877, -142.081024,   -0.000621,   -0.001974,  582.817444,   41.766983, -145.366440,
  590.502930,    0.000000,    0.000000,    0.000000,    0.000000,    0.000000,    0.000000,
/home/pi/depthai-experiments/triangulation-3D-visualizer/models/face-detection-retail-0004/face-detection-retail-0004.json
depthai: Calibration file is not specified, will use default setting;
config_h2d json:
{"_board":{"calib_data":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"mesh_left":[0.0],"mesh_right":[0.0]},"_load_inBlob":true,"_pipeline":{"_streams":[{"name":"metaout"},{"name":"previewout"}]},"ai":{"NCEs":2,"NN_config":{"NN_family":"mobilenet","confidence_threshold":0.5,"output_format":"detection"},"blob0_size":1335872,"blob1_size":532288,"calc_dist_to_bb":false,"camera_input":"left_right","cmx_slices":14,"keep_aspect_ratio":true,"num_stages":2,"shaves":14},"app":{"sync_sequence_numbers":false,"sync_video_meta_streams":false,"usb_chunk_KiB":64},"board":{"clear-eeprom":false,"left_fov_deg":69.0,"left_to_rgb_distance_m":0.0,"left_to_right_distance_m":0.03500000014901161,"name":"","override-eeprom":false,"revision":"","rgb_fov_deg":69.0,"stereo_center_crop":false,"store-to-eeprom":false,"swap-left-and-right-cameras":false},"camera":{"mono":{"fps":30.0,"resolution_h":720,"resolution_w":1280},"rgb":{"fps":30.0,"resolution_h":1080,"resolution_w":1920}},"depth":{"depth_limit_mm":10000,"lr_check":false,"median_kernel_size":7,"padding_factor":0.30000001192092896,"warp_rectify":{"edge_fill_color":-1,"mirror_frame":true,"use_mesh":false}},"ot":{"confidence_threshold":0.5,"max_tracklets":20}}
size of input string json_config_obj to config_h2d is ->Attempting to open stream config_h2d
Successfully opened stream config_h2d with ID #1!
Writing 1048576 bytes to config_h2d
!!! XLink write successful: config_h2d (1048576)
Closing stream config_h2d: ...
Closing stream config_h2d: DONE.
Creating observer stream host_capture: ...
Attempting to open stream host_capture
Successfully opened stream host_capture with ID #0!
Creating observer stream host_capture: DONE.
Attempting to open stream inBlob
Successfully opened stream inBlob with ID #1!
Writing 1335872 bytes to inBlob
!!! XLink write successful: inBlob (1335872)
Closing stream inBlob: ...
Closing stream inBlob: DONE.
depthai: done sending Blob file /home/pi/depthai-experiments/triangulation-3D-visualizer/models/face-detection-retail-0004/face-detection-retail-0004.blob
Attempting to open stream outBlob
Successfully opened stream outBlob with ID #2!
Closing stream outBlob: ...
Closing stream outBlob: DONE.
CNN to depth bounding-box mapping: start(280, 0), max_size(720, 720)
Attempting to open stream inBlob
Successfully opened stream inBlob with ID #1!
Writing 532288 bytes to inBlob
!!! XLink write successful: inBlob (532288)
Closing stream inBlob: ...
Closing stream inBlob: DONE.
depthai: done sending Blob file /home/pi/depthai-experiments/triangulation-3D-visualizer/models/landmarks-regression-retail-0009/landmarks-regression-retail-0009.blob
Attempting to open stream outBlob
Successfully opened stream outBlob with ID #2!
Closing stream outBlob: ...
Closing stream outBlob: DONE.
Opening stream for read: metaout
Attempting to open stream metaout
Successfully opened stream metaout with ID #1!
Starting thread for stream: metaout
Opening stream for read: previewout
Attempting to open stream previewout
Started thread for stream: metaout
Successfully opened stream previewout with ID #2!
Starting thread for stream: previewout
Started thread for stream: previewout
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    initialize_OpenGL()
  File "/home/pi/depthai-experiments/triangulation-3D-visualizer/visualizer.py", line 119, in initialize_OpenGL
    gluPerspective(45, (1.0 * display[0] / display[1]), 0.1, 50.0)
  File "/home/pi/venv2/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function gluPerspective, check for bool(gluPerspective) before calling
=== New data in observer stream host_capture, size: 4
Writing 4 bytes to host_capture
!!! XLink write successful: host_capture (4)
Stopping threads: ...
E: [global] [    851885] [Scheduler00Thr] dispatcherEventSend:53	Write failed (header) (err -1) | event XLINK_READ_REL_REQ

E: [xLink] [    851885] [Scheduler00Thr] sendEvents:1027	Event sending failed
E: [global] [    851885] [python3] addEvent:264	Condition failed: event->header.flags.bitField.ack != 1
E: [global] [    851885] [python3] addEventWithPerf:276	 addEvent(event) method call failed with an error: 3
E: [global] [    851885] [python3] XLinkReadData:156	Condition failed: (addEventWithPerf(&event, &opTime))
Device get data failed: 7
Closing stream metaout: ...
Closing stream metaout: DONE.
Thread for metaout finished.
E: [global] [    851886] [Scheduler00Thr] dispatcherEventSend:53	Write failed (header) (err -1) | event XLINK_CLOSE_STREAM_REQ

E: [xLink] [    851886] [Scheduler00Thr] sendEvents:1027	Event sending failed
Closing stream previewout: ...
E: [global] [    851887] [Scheduler00Thr] dispatcherEventSend:53	Write failed (header) (err -1) | event XLINK_CLOSE_STREAM_REQ

E: [xLink] [    851887] [Scheduler00Thr] sendEvents:1027	Event sending failed
Closing stream previewout: DONE.
Thread for previewout finished.
Stopping threads: DONE 0.004s.
Closing all observer streams: ...
Closing stream host_capture: ...
Closing stream host_capture: DONE.
Closing all observer streams: DONE.
Reseting device: 0.
E: [global] [    851888] [Scheduler00Thr] dispatcherEventSend:53	Write failed (header) (err -1) | event XLINK_RESET_REQ

E: [xLink] [    851888] [Scheduler00Thr] sendEvents:1027	Event sending failed
Reseting: DONE.
```

The error defined is while using gluPerspective from pyopengl version "3.1.5"

**Comment by Luxonis-Brandon** [comment]
Thanks.  Checking.  Sorry about the delay.

**Comment by dhruvsheth-ai** [comment]
Steven Resolved the issue. Thanks!
